# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16a1864f75a101a755bc3524baf0b089157a6b0da34d14919a10c978715c3c2aa12419cb3f3d8677a4a6e1bd9f0f044396f51235156e1b2f52effd22383eee76

test:
  secret_key_base: ef2a7ca8b67c3f5053f2b2b7e61aea6bbfb8e66de43c07aeb023b62d5c89cd840fd8d79736739dc48c560b4547d005409c1bd90ea7d54a71ce15a96548300bb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
